# Generated by Django 6.1.1 on 2026-09-27 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_grant_deposit_capabilities"),
        ("billing", "0002_invoices_ledger_deposits"),
        ("leases", "0002_lease_overlap_uses_actual_end"),
        ("properties", "0004_branding_and_branches"),
        ("tenants", "0002_tenant_org_name_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PAYBILL", "M-Pesa Paybill"),
                            ("TILL", "M-Pesa Till"),
                            ("BANK", "Bank account"),
                            ("MPESA_PERSONAL", "Personal M-Pesa"),
                            ("CASH", "Cash"),
                        ],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="account number"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=80, verbose_name="display name"),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("MPESA", "M-Pesa"),
                            ("CASH", "Cash"),
                            ("BANK", "Bank"),
                            ("CHEQUE", "Cheque"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                        verbose_name="method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("CONFIRMED", "Confirmed"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="PENDING_REVIEW",
                        editable=False,
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("paid_at", models.DateField(verbose_name="date paid")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="reference"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "reversed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "reversal_reason",
                    models.CharField(blank=True, editable=False, max_length=300),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="payments.paymentaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_allocations",
                        to="billing.invoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="PropertyPaymentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="payments.paymentaccount",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_accounts",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        editable=False, max_length=30, verbose_name="receipt number"
                    ),
                ),
                ("issued_at", models.DateTimeField(editable=False)),
                ("pdf", models.FileField(editable=False, upload_to="receipts/%Y/")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt",
                        to="payments.payment",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="paymentaccount",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                models.F("type"),
                models.F("number"),
                name="payments_paymentaccount_org_type_number_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["organization", "status"], name="payments_pa_organiz_1d83a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["lease", "paid_at"], name="payments_pa_lease_i_0ab1aa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="payments_payment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.UniqueConstraint(
                models.F("payment"),
                models.F("invoice"),
                name="payments_paymentallocation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="payments_paymentallocation_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertypaymentaccount",
            constraint=models.UniqueConstraint(
                models.F("property"),
                models.F("payment_account"),
                name="payments_propertypaymentaccount_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertypaymentaccount",
            constraint=models.UniqueConstraint(
                models.F("property"),
                condition=models.Q(("is_default", True)),
                name="payments_propertypaymentaccount_one_default",
            ),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                models.F("number"),
                name="payments_receipt_org_number_unique",
            ),
        ),
    ]
