# Generated by Django 6.1.1 on 2026-09-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="share_token",
            field=models.CharField(
                blank=True, editable=False, max_length=32, null=True, unique=True
            ),
        ),
    ]
