# Generated by Django 6.1.1 on 2026-09-27 07:48

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_organization_billing_settings"),
        ("billing", "0001_initial"),
        ("leases", "0002_lease_overlap_uses_actual_end"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chargetype",
            name="is_taxable",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="chargetype",
            name="tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=3, editable=False, max_digits=6, null=True
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        verbose_name="invoice number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("PARTIALLY_PAID", "Partly paid"),
                            ("PAID", "Paid"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        editable=False,
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="period start")),
                ("period_end", models.DateField(verbose_name="period end")),
                (
                    "issue_date",
                    models.DateField(blank=True, null=True, verbose_name="issue date"),
                ),
                ("due_date", models.DateField(verbose_name="due date")),
                ("overdue_after", models.DateField(verbose_name="overdue after")),
                (
                    "currency",
                    models.CharField(default="KES", editable=False, max_length=3),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=14
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=300, verbose_name="notes"),
                ),
                (
                    "issued_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("void_reason", models.TextField(blank=True, editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="description"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        max_digits=14,
                        verbose_name="quantity",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="unit price"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("service_start", models.DateField(blank=True, null=True)),
                ("service_end", models.DateField(blank=True, null=True)),
                (
                    "billing_month",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                ("is_void", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "charge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="billing.chargetype",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="billing.invoice",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateField(verbose_name="date")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("OPENING_BALANCE", "Balance brought forward"),
                            ("INVOICE", "Invoice"),
                            ("INVOICE_VOID", "Invoice voided"),
                            ("PAYMENT", "Payment"),
                            ("PAYMENT_REVERSAL", "Payment reversed"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("DEPOSIT_APPLIED", "Deposit applied"),
                            ("REVERSAL", "Correction"),
                        ],
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "reason",
                    models.CharField(blank=True, max_length=300, verbose_name="reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="billing.invoice",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="billing.ledgerentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ledger entries",
                "ordering": ["entry_date", "pk"],
            },
        ),
        migrations.CreateModel(
            name="DepositEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit_type",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent deposit"),
                            ("WATER", "Water deposit"),
                            ("ELECTRICITY", "Electricity deposit"),
                            ("OTHER", "Other deposit"),
                        ],
                        default="RENT",
                        max_length=12,
                        verbose_name="deposit",
                    ),
                ),
                ("entry_date", models.DateField(verbose_name="date")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DEPOSIT_RECEIVED", "Deposit received"),
                            ("DEPOSIT_DEDUCTION", "Deduction"),
                            ("DEPOSIT_REFUNDED", "Refunded"),
                            ("DEPOSIT_TRANSFERRED", "Transferred"),
                            ("REVERSAL", "Correction"),
                        ],
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "reason",
                    models.CharField(blank=True, max_length=300, verbose_name="reason"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="reference"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "counterpart",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="billing.depositentry",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_entries",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="billing.depositentry",
                    ),
                ),
                (
                    "ledger_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_entry",
                        to="billing.ledgerentry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "deposit entries",
                "ordering": ["entry_date", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["organization", "status", "overdue_after"],
                name="billing_inv_organiz_0315b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["lease", "period_start"], name="billing_inv_lease_i_b6288f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                models.F("number"),
                condition=models.Q(("number", ""), _negated=True),
                name="billing_invoice_org_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="billing_invoice_period_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total",
                        django.db.models.expressions.CombinedExpression(
                            models.F("subtotal"), "+", models.F("tax_total")
                        ),
                    )
                ),
                name="billing_invoice_total_sum",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0), ("tax_total__gte", 0)),
                name="billing_invoice_amounts_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_paid__gte", 0), ("amount_paid__lte", models.F("total"))
                ),
                name="billing_invoice_paid_within_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "DRAFT"),
                    models.Q(("number", ""), _negated=True),
                    _connector="OR",
                ),
                name="billing_invoice_issued_has_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.UniqueConstraint(
                models.F("lease"),
                models.F("billing_month"),
                models.F("charge_type"),
                condition=models.Q(("is_void", False)),
                name="billing_invoiceline_billed_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount__gte", 0), ("quantity__gt", 0), ("tax_amount__gte", 0)
                ),
                name="billing_invoiceline_amounts_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("service_start__isnull", True),
                    ("service_end__isnull", True),
                    ("service_end__gte", models.F("service_start")),
                    _connector="OR",
                ),
                name="billing_invoiceline_service_order",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["lease", "entry_date"], name="billing_led_lease_i_37cd7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["organization", "kind"], name="billing_led_organiz_b6819d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="billing_ledger_amount_not_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind__in", ["INVOICE", "PAYMENT_REVERSAL"]), _negated=True
                    ),
                    ("amount__gt", 0),
                    _connector="OR",
                ),
                name="billing_ledger_debit_kinds_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind__in", ["INVOICE_VOID", "PAYMENT", "DEPOSIT_APPLIED"]),
                        _negated=True,
                    ),
                    ("amount__lt", 0),
                    _connector="OR",
                ),
                name="billing_ledger_credit_kinds_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "REVERSAL"), ("reversal_of__isnull", False)),
                    models.Q(
                        models.Q(("kind", "REVERSAL"), _negated=True),
                        ("reversal_of__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="billing_ledger_reversal_has_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind__in", ["INVOICE", "INVOICE_VOID"]), _negated=True),
                    ("invoice__isnull", False),
                    _connector="OR",
                ),
                name="billing_ledger_invoice_kinds_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.UniqueConstraint(
                models.F("invoice"),
                models.F("kind"),
                condition=models.Q(("kind__in", ["INVOICE", "INVOICE_VOID"])),
                name="billing_ledger_invoice_posted_once",
            ),
        ),
        migrations.AddIndex(
            model_name="depositentry",
            index=models.Index(
                fields=["lease", "deposit_type"], name="billing_dep_lease_i_aa799b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="depositentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="billing_deposit_amount_not_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "DEPOSIT_RECEIVED"), _negated=True),
                    ("amount__gt", 0),
                    _connector="OR",
                ),
                name="billing_deposit_received_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind__in", ["DEPOSIT_DEDUCTION", "DEPOSIT_REFUNDED"]),
                        _negated=True,
                    ),
                    ("amount__lt", 0),
                    _connector="OR",
                ),
                name="billing_deposit_outgoing_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "DEPOSIT_DEDUCTION"), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="billing_deposit_deduction_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "REVERSAL"), ("reversal_of__isnull", False)),
                    models.Q(
                        models.Q(("kind", "REVERSAL"), _negated=True),
                        ("reversal_of__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="billing_deposit_reversal_has_target",
            ),
        ),
    ]
