# Generated by Django 6.1.1 on 2026-09-27 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_grant_deposit_capabilities"),
        ("billing", "0002_invoices_ledger_deposits"),
        ("leases", "0002_lease_overlap_uses_actual_end"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="payments.payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind__in", ["PAYMENT", "PAYMENT_REVERSAL"]), _negated=True
                    ),
                    ("payment__isnull", False),
                    _connector="OR",
                ),
                name="billing_ledger_payment_kinds_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.UniqueConstraint(
                models.F("payment"),
                models.F("kind"),
                condition=models.Q(("kind__in", ["PAYMENT", "PAYMENT_REVERSAL"])),
                name="billing_ledger_payment_posted_once",
            ),
        ),
    ]
