# Generated by Django 6.1.1 on 2026-09-29 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_ledgerentry_payment"),
        ("inspections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositentry",
            name="condition_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_entries",
                to="inspections.conditionreport",
            ),
        ),
    ]
