# Generated by Django 6.1.1 on 2026-09-29 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_grant_follow_up_capability"),
        ("billing", "0004_depositentry_condition_report"),
        ("leases", "0003_billing_frequency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("SPOKE", "Spoke to them"),
                            ("NO_ANSWER", "No answer"),
                            ("PROMISED", "Promised to pay"),
                            ("DISPUTED", "Disputes the amount"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                        verbose_name="outcome",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="note"),
                ),
                (
                    "promised_on",
                    models.DateField(blank=True, null=True, verbose_name="will pay by"),
                ),
                (
                    "promised_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="amount promised",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_ups",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["lease", "created_at"],
                        name="billing_fol_lease_i_fc3e74_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("outcome", "PROMISED"), ("promised_on__isnull", False)
                            ),
                            models.Q(
                                models.Q(("outcome", "PROMISED"), _negated=True),
                                ("promised_amount__isnull", True),
                                ("promised_on__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="billing_followup_promise_has_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("promised_amount__isnull", True),
                            ("promised_amount__gt", 0),
                            _connector="OR",
                        ),
                        name="billing_followup_promised_amount_positive",
                    ),
                ],
            },
        ),
    ]
