# Generated by Django 6.1.1 on 2026-09-29 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("ok", models.BooleanField(null=True)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["name", "-started_at"], name="core_jobrun_name_started"
                    )
                ],
            },
        ),
    ]
