# Generated by Django 6.1.1 on 2026-09-29 19:03

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_mfa"),
        ("properties", "0005_property_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=60, verbose_name="name")),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "expense categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "kra_pin",
                    models.CharField(blank=True, max_length=11, verbose_name="KRA PIN"),
                ),
                (
                    "payment_details",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="how they are paid"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="note"),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("number", models.CharField(editable=False, max_length=30)),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="what was paid for"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                ("paid_on", models.DateField(verbose_name="date paid")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("MPESA", "M-Pesa"),
                            ("BANK", "Bank transfer"),
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("OTHER", "Other"),
                        ],
                        default="MPESA",
                        max_length=10,
                        verbose_name="paid by",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="reference"
                    ),
                ),
                (
                    "reference_key",
                    models.CharField(blank=True, editable=False, max_length=60),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True, editable=False, upload_to="expense-receipts/%Y/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Waiting for approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("VOIDED", "Voided"),
                        ],
                        default="SUBMITTED",
                        editable=False,
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "reject_reason",
                    models.CharField(blank=True, editable=False, max_length=300),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "void_reason",
                    models.CharField(blank=True, editable=False, max_length=300),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="properties.property",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="expenses.expensecategory",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="expenses.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_on", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("archived_at__isnull", True)),
                name="expenses_category_name_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["organization", "status", "paid_on"],
                name="expenses_ex_organiz_fcdc31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["property", "paid_on"], name="expenses_ex_propert_f7f1bb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                models.F("number"),
                name="expenses_expense_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                models.F("reference_key"),
                condition=models.Q(
                    ("status__in", ["SUBMITTED", "APPROVED"]),
                    models.Q(("reference_key", ""), _negated=True),
                ),
                name="expenses_expense_reference_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="expenses_expense_amount_positive",
            ),
        ),
    ]
