# Generated by Django 6.1.1 on 2026-09-29 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="maintenance_request",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="maintenance.maintenancerequest",
            ),
        ),
    ]
