# Generated by Django 6.1.1 on 2026-09-28 19:34

import django.db.models.deletion
import mpesa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_organization_quiet_hours"),
        ("payments", "0002_receipt_share_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DarajaCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("SANDBOX", "Sandbox (testing)"),
                            ("PRODUCTION", "Live"),
                        ],
                        default="SANDBOX",
                        max_length=10,
                        verbose_name="environment",
                    ),
                ),
                (
                    "shortcode",
                    models.CharField(max_length=10, verbose_name="shortcode"),
                ),
                ("consumer_key_encrypted", models.TextField(blank=True)),
                ("consumer_secret_encrypted", models.TextField(blank=True)),
                ("passkey_encrypted", models.TextField(blank=True)),
                (
                    "callback_token",
                    models.CharField(
                        default=mpesa.models.new_callback_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("urls_registered_at", models.DateTimeField(blank=True, null=True)),
                ("registration_error", models.CharField(blank=True, max_length=300)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "payment_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daraja",
                        to="payments.paymentaccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Daraja credentials",
            },
        ),
    ]
