# Generated by Django 6.1.1 on 2026-09-28 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_organization_quiet_hours"),
        ("leases", "0002_lease_overlap_uses_actual_end"),
        ("mpesa", "0001_daraja_credentials"),
        ("payments", "0002_receipt_share_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("C2B", "Paybill / Till"), ("STK", "Payment request")],
                        default="C2B",
                        max_length=3,
                    ),
                ),
                (
                    "trans_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="M-Pesa code"
                    ),
                ),
                ("trans_type", models.CharField(blank=True, max_length=40)),
                ("shortcode", models.CharField(blank=True, max_length=10)),
                (
                    "bill_ref",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="account reference"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                ("paid_at", models.DateTimeField(verbose_name="paid at")),
                ("msisdn_raw", models.CharField(blank=True, max_length=80)),
                (
                    "msisdn_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("payer_phone", models.CharField(blank=True, max_length=16)),
                ("payer_name", models.CharField(blank=True, max_length=150)),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("MATCHED", "Matched"),
                            ("UNMATCHED", "Waiting to be matched"),
                            ("FLAGGED", "Flagged"),
                            ("IGNORED", "Ignored"),
                        ],
                        default="RECEIVED",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "matched_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REFERENCE", "Account reference"),
                            ("MANUAL", "By hand"),
                            ("STK", "Payment request"),
                        ],
                        max_length=10,
                    ),
                ),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "matched_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mpesa_transaction",
                        to="payments.payment",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mpesa_transactions",
                        to="payments.paymentaccount",
                    ),
                ),
                (
                    "suggested_lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leases.lease",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="mpesa_mpesa_organiz_9c9d8b_idx",
                    ),
                    models.Index(
                        fields=["payment_account", "paid_at"],
                        name="mpesa_mpesa_payment_4d6575_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="mpesa_transaction_amount_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "MATCHED"), _negated=True),
                            ("payment__isnull", False),
                            _connector="OR",
                        ),
                        name="mpesa_transaction_matched_has_payment",
                    ),
                ],
            },
        ),
    ]
