# Generated by Django 6.1.1 on 2026-09-28 21:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_organization_quiet_hours"),
        ("leases", "0002_lease_overlap_uses_actual_end"),
        ("mpesa", "0002_transactions"),
        ("payments", "0002_receipt_share_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("phone", models.CharField(max_length=16, verbose_name="phone")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                ("account_reference", models.CharField(max_length=12)),
                ("merchant_request_id", models.CharField(blank=True, max_length=60)),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, max_length=60, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting for the tenant"),
                            ("PAID", "Paid"),
                            ("FAILED", "Not paid"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("result_code", models.CharField(blank=True, max_length=20)),
                ("result_desc", models.CharField(blank=True, max_length=300)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stk_requests",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stk_requests",
                        to="payments.paymentaccount",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stk_request",
                        to="mpesa.mpesatransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="mpesa_stkre_organiz_9637f2_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="mpesa_stkrequest_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "PAID"), _negated=True),
                            ("transaction__isnull", False),
                            _connector="OR",
                        ),
                        name="mpesa_stkrequest_paid_has_transaction",
                    ),
                ],
            },
        ),
    ]
