# Generated by Django 6.1.1 on 2026-09-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpesa", "0004_pay_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpesatransaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("C2B", "Paybill / Till"),
                    ("STK", "Payment request"),
                    ("STM", "Statement import"),
                ],
                default="C2B",
                max_length=3,
            ),
        ),
    ]
