# Generated by Django 6.1.1 on 2026-09-26 12:56

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("INDIVIDUAL", "Individual"), ("COMPANY", "Company")],
                        default="INDIVIDUAL",
                        max_length=12,
                        verbose_name="type",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="contact person"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="E.164, e.g. +254712345678",
                        max_length=16,
                        verbose_name="phone",
                    ),
                ),
                (
                    "alt_phone",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="other phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROSPECT", "Prospect"),
                            ("ACTIVE", "Active"),
                            ("FORMER", "Former"),
                        ],
                        default="PROSPECT",
                        editable=False,
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NATIONAL_ID", "National ID"),
                            ("PASSPORT", "Passport"),
                            ("ALIEN_ID", "Alien ID"),
                            ("COMPANY_REG", "Company registration"),
                        ],
                        max_length=12,
                        verbose_name="ID type",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="ID / registration number",
                    ),
                ),
                (
                    "kra_pin",
                    models.CharField(blank=True, max_length=11, verbose_name="KRA PIN"),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="emergency contact"
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        verbose_name="emergency contact phone",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenants",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "phone"],
                        name="tenants_ten_organiz_e49f6b_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="tenants_ten_organiz_41f276_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("organization"),
                        models.F("id_type"),
                        django.db.models.functions.text.Upper("id_number"),
                        condition=models.Q(("id_number", ""), _negated=True),
                        name="tenants_tenant_org_id_number_unique",
                    )
                ],
            },
        ),
    ]
