# Generated by Django 6.1.1 on 2026-09-26 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("tenants", "0001_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["organization", "name"], name="tenants_ten_organiz_e6dc2d_idx"
            ),
        ),
    ]
