# Generated by Django 6.1.1 on 2026-09-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_org_name_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("sw", "Swahili")],
                default="en",
                max_length=2,
                verbose_name="message language",
            ),
        ),
    ]
