# Generated by Django 6.1.1 on 2026-09-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="kind",
            field=models.CharField(
                choices=[
                    ("UNITS", "Units"),
                    ("TENANTS", "Tenants"),
                    ("BALANCES", "Opening balances"),
                ],
                max_length=10,
            ),
        ),
    ]
