# Generated by Django 6.1.1 on 2026-09-26 09:43

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="properties",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="properties.property"
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membershipcapability",
            name="capability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.capability"
            ),
        ),
        migrations.AddField(
            model_name="membershipcapability",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membershipcapability",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overrides",
                to="accounts.membership",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations",
                to="accounts.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["phone", "purpose", "-created_at"],
                name="accounts_ot_phone_b1f230_idx",
            ),
        ),
        migrations.AddField(
            model_name="propertyaccess",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_access",
                to="accounts.membership",
            ),
        ),
        migrations.AddField(
            model_name="propertyaccess",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roles",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="accounts.role",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations",
                to="accounts.role",
            ),
        ),
        migrations.AddField(
            model_name="rolecapability",
            name="capability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.capability"
            ),
        ),
        migrations.AddField(
            model_name="rolecapability",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.role"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="capabilities",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                through="accounts.RoleCapability",
                to="accounts.capability",
            ),
        ),
        migrations.AddField(
            model_name="roletemplate",
            name="capabilities",
            field=models.ManyToManyField(
                blank=True, related_name="templates", to="accounts.capability"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="based_on_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roles",
                to="accounts.roletemplate",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email__isnull", False)),
                name="accounts_user_email_unique_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipcapability",
            constraint=models.UniqueConstraint(
                fields=("membership", "capability"), name="accounts_membercap_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyaccess",
            constraint=models.UniqueConstraint(
                fields=("membership", "property"), name="accounts_propaccess_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"), name="accounts_membership_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolecapability",
            constraint=models.UniqueConstraint(
                fields=("role", "capability"), name="accounts_rolecap_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                django.db.models.functions.text.Lower("name"),
                name="accounts_role_org_name_unique_ci",
            ),
        ),
    ]
