# Generated by Django 6.1.1 on 2026-09-26 20:25

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="brand_color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$", "Use a hex colour like #1A73E8."
                    )
                ],
                verbose_name="brand colour",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="brand_name",
            field=models.CharField(
                blank=True,
                help_text="Shown to tenants instead of the organization name.",
                max_length=150,
                verbose_name="brand name",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="document_footer",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="document footer"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to="org-logos/", verbose_name="logo"
            ),
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=16, verbose_name="phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "branches",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("organization"),
                        django.db.models.functions.text.Upper("name"),
                        name="accounts_branch_org_name_unique",
                    )
                ],
            },
        ),
    ]
