# Generated by Django 6.1.1 on 2026-09-27 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_branding_and_branches"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="invoice_lead_days",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="How many days before the month starts its invoices go out.",
                validators=[django.core.validators.MaxValueValidator(28)],
                verbose_name="invoice lead days",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="prorate_partial_months",
            field=models.BooleanField(
                default=True, verbose_name="prorate partial months"
            ),
        ),
    ]
