# Generated by Django 6.1.1 on 2026-09-27 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_grant_deposit_capabilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="quiet_hours_end",
            field=models.TimeField(
                default=datetime.time(7, 0), verbose_name="quiet hours end"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="quiet_hours_start",
            field=models.TimeField(
                default=datetime.time(21, 0), verbose_name="quiet hours start"
            ),
        ),
    ]
