"""Kenyan reference data (doc 14 D8: structured addresses so reports can group by area)."""

from django.db import models


class County(models.TextChoices):
    MOMBASA = "MOMBASA", "Mombasa"
    KWALE = "KWALE", "Kwale"
    KILIFI = "KILIFI", "Kilifi"
    TANA_RIVER = "TANA_RIVER", "Tana River"
    LAMU = "LAMU", "Lamu"
    TAITA_TAVETA = "TAITA_TAVETA", "Taita-Taveta"
    GARISSA = "GARISSA", "Garissa"
    WAJIR = "WAJIR", "Wajir"
    MANDERA = "MANDERA", "Mandera"
    MARSABIT = "MARSABIT", "Marsabit"
    ISIOLO = "ISIOLO", "Isiolo"
    MERU = "MERU", "Meru"
    THARAKA_NITHI = "THARAKA_NITHI", "Tharaka-Nithi"
    EMBU = "EMBU", "Embu"
    KITUI = "KITUI", "Kitui"
    MACHAKOS = "MACHAKOS", "Machakos"
    MAKUENI = "MAKUENI", "Makueni"
    NYANDARUA = "NYANDARUA", "Nyandarua"
    NYERI = "NYERI", "Nyeri"
    KIRINYAGA = "KIRINYAGA", "Kirinyaga"
    MURANGA = "MURANGA", "Murang'a"
    KIAMBU = "KIAMBU", "Kiambu"
    TURKANA = "TURKANA", "Turkana"
    WEST_POKOT = "WEST_POKOT", "West Pokot"
    SAMBURU = "SAMBURU", "Samburu"
    TRANS_NZOIA = "TRANS_NZOIA", "Trans-Nzoia"
    UASIN_GISHU = "UASIN_GISHU", "Uasin Gishu"
    ELGEYO_MARAKWET = "ELGEYO_MARAKWET", "Elgeyo-Marakwet"
    NANDI = "NANDI", "Nandi"
    BARINGO = "BARINGO", "Baringo"
    LAIKIPIA = "LAIKIPIA", "Laikipia"
    NAKURU = "NAKURU", "Nakuru"
    NAROK = "NAROK", "Narok"
    KAJIADO = "KAJIADO", "Kajiado"
    KERICHO = "KERICHO", "Kericho"
    BOMET = "BOMET", "Bomet"
    KAKAMEGA = "KAKAMEGA", "Kakamega"
    VIHIGA = "VIHIGA", "Vihiga"
    BUNGOMA = "BUNGOMA", "Bungoma"
    BUSIA = "BUSIA", "Busia"
    SIAYA = "SIAYA", "Siaya"
    KISUMU = "KISUMU", "Kisumu"
    HOMA_BAY = "HOMA_BAY", "Homa Bay"
    MIGORI = "MIGORI", "Migori"
    KISII = "KISII", "Kisii"
    NYAMIRA = "NYAMIRA", "Nyamira"
    NAIROBI = "NAIROBI", "Nairobi"
