# Generated by Django 6.1.1 on 2026-09-29 16:17

import django.db.models.deletion
import django.utils.timezone
import support.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_mfa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MAJOR", "Major"),
                            ("OUTAGE", "Outage"),
                        ],
                        default="MINOR",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVESTIGATING", "Investigating"),
                            ("IDENTIFIED", "Identified"),
                            ("MONITORING", "Monitoring"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="INVESTIGATING",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVESTIGATING", "Investigating"),
                            ("IDENTIFIED", "Identified"),
                            ("MONITORING", "Monitoring"),
                            ("RESOLVED", "Resolved"),
                        ],
                        max_length=15,
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                ("posted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="support.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("QUESTION", "A question"),
                            ("PROBLEM", "Something is not working"),
                            ("IMPORT_HELP", "Import my data for me"),
                        ],
                        default="QUESTION",
                        max_length=12,
                    ),
                ),
                ("subject", models.CharField(max_length=150)),
                ("message", models.TextField(max_length=5000)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        editable=False,
                        upload_to=support.models._attachment_path,
                    ),
                ),
                (
                    "attachment_name",
                    models.CharField(blank=True, editable=False, max_length=200),
                ),
                ("page", models.CharField(blank=True, max_length=300)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("WAITING", "Waiting on the customer"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("internal_note", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_requests",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
