# Generated by Django 6.1.1 on 2026-09-29 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0008_letter_settings"),
        ("leases", "0002_lease_overlap_uses_actual_end"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenancyLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False, max_length=30, verbose_name="letter number"
                    ),
                ),
                ("issued_at", models.DateTimeField(editable=False)),
                ("facts", models.JSONField(editable=False)),
                ("pdf", models.FileField(editable=False, upload_to="letters/%Y/")),
                (
                    "verify_code",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "withdraw_reason",
                    models.CharField(blank=True, editable=False, max_length=300),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="letters",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("organization"),
                        models.F("number"),
                        name="letters_letter_org_number_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("withdrawn_at__isnull", True),
                            models.Q(("withdraw_reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="letters_letter_withdrawn_has_reason",
                    ),
                ],
            },
        ),
    ]
