# Generated by Django 6.1.1 on 2026-09-26 09:43

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("code", models.CharField(max_length=10, verbose_name="code")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("APARTMENT_BLOCK", "Apartment block"),
                            ("ESTATE", "Estate"),
                            ("COMMERCIAL", "Commercial"),
                            ("MIXED_USE", "Mixed-use"),
                            ("SINGLE_HOUSE", "Single house"),
                        ],
                        default="APARTMENT_BLOCK",
                        max_length=20,
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("organization"),
                        django.db.models.functions.text.Upper("code"),
                        name="properties_property_org_code_unique",
                    )
                ],
            },
        ),
    ]
