# Generated by Django 6.1.1 on 2026-09-26 12:39

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import re
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="area",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="estate / area"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="county",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MOMBASA", "Mombasa"),
                    ("KWALE", "Kwale"),
                    ("KILIFI", "Kilifi"),
                    ("TANA_RIVER", "Tana River"),
                    ("LAMU", "Lamu"),
                    ("TAITA_TAVETA", "Taita-Taveta"),
                    ("GARISSA", "Garissa"),
                    ("WAJIR", "Wajir"),
                    ("MANDERA", "Mandera"),
                    ("MARSABIT", "Marsabit"),
                    ("ISIOLO", "Isiolo"),
                    ("MERU", "Meru"),
                    ("THARAKA_NITHI", "Tharaka-Nithi"),
                    ("EMBU", "Embu"),
                    ("KITUI", "Kitui"),
                    ("MACHAKOS", "Machakos"),
                    ("MAKUENI", "Makueni"),
                    ("NYANDARUA", "Nyandarua"),
                    ("NYERI", "Nyeri"),
                    ("KIRINYAGA", "Kirinyaga"),
                    ("MURANGA", "Murang'a"),
                    ("KIAMBU", "Kiambu"),
                    ("TURKANA", "Turkana"),
                    ("WEST_POKOT", "West Pokot"),
                    ("SAMBURU", "Samburu"),
                    ("TRANS_NZOIA", "Trans-Nzoia"),
                    ("UASIN_GISHU", "Uasin Gishu"),
                    ("ELGEYO_MARAKWET", "Elgeyo-Marakwet"),
                    ("NANDI", "Nandi"),
                    ("BARINGO", "Baringo"),
                    ("LAIKIPIA", "Laikipia"),
                    ("NAKURU", "Nakuru"),
                    ("NAROK", "Narok"),
                    ("KAJIADO", "Kajiado"),
                    ("KERICHO", "Kericho"),
                    ("BOMET", "Bomet"),
                    ("KAKAMEGA", "Kakamega"),
                    ("VIHIGA", "Vihiga"),
                    ("BUNGOMA", "Bungoma"),
                    ("BUSIA", "Busia"),
                    ("SIAYA", "Siaya"),
                    ("KISUMU", "Kisumu"),
                    ("HOMA_BAY", "Homa Bay"),
                    ("MIGORI", "Migori"),
                    ("KISII", "Kisii"),
                    ("NYAMIRA", "Nyamira"),
                    ("NAIROBI", "Nairobi"),
                ],
                max_length=20,
                verbose_name="county",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="street",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="street / landmark"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="sub_county",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="sub-county / ward"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="category",
            field=models.CharField(
                choices=[
                    ("APARTMENT_BLOCK", "Apartment block"),
                    ("ESTATE", "Estate"),
                    ("COMMERCIAL", "Commercial"),
                    ("MIXED_USE", "Mixed-use"),
                    ("SINGLE_HOUSE", "Single house"),
                ],
                default="APARTMENT_BLOCK",
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="code",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[A-Z0-9]{1,10}$"),
                        "Use 1–10 letters or digits, e.g. GV.",
                    )
                ],
                verbose_name="code",
            ),
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buildings",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[A-Z0-9](?:[A-Z0-9-]{0,8}[A-Z0-9])?$"),
                                "Use 1–10 letters, digits or inner hyphens, e.g. A102 or B-12.",
                            )
                        ],
                        verbose_name="unit code",
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Apartment"),
                            ("HOUSE", "House"),
                            ("BEDSITTER", "Bedsitter"),
                            ("STUDIO", "Studio"),
                            ("SHOP", "Shop"),
                            ("OFFICE", "Office"),
                            ("WAREHOUSE", "Warehouse"),
                            ("PARKING", "Parking"),
                            ("BED_SPACE", "Bed space"),
                            ("OTHER", "Other"),
                        ],
                        default="APARTMENT",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "type_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional, e.g. 2 bedroom",
                        max_length=60,
                        verbose_name="label",
                    ),
                ),
                (
                    "manual_status",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("RESERVED", "Reserved"),
                            ("UNDER_MAINTENANCE", "Under maintenance"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("payment_reference", models.CharField(editable=False, max_length=21)),
                (
                    "list_rent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="asking rent",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="properties.building",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["property__name", "code"],
            },
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(
                models.F("property"),
                django.db.models.functions.text.Upper("name"),
                name="properties_building_property_name_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=models.Index(
                fields=["organization", "manual_status"],
                name="properties__organiz_0c46ac_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                models.F("property"),
                django.db.models.functions.text.Upper("code"),
                name="properties_unit_property_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                django.db.models.functions.text.Upper("payment_reference"),
                name="properties_unit_org_payment_reference_unique",
            ),
        ),
    ]
