# Generated by Django 6.1.1 on 2026-09-26 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_branding_and_branches"),
        ("properties", "0003_unit_share_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="accounts.branch",
            ),
        ),
    ]
