# Generated by Django 6.1.1 on 2026-09-29 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_mfa"),
        ("leases", "0003_billing_frequency"),
        ("payments", "0002_receipt_share_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BANK", "Bank statement"),
                            ("MPESA", "M-Pesa statement"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "Checked, not imported"),
                            ("APPLIED", "Imported"),
                            ("DISCARDED", "Discarded"),
                        ],
                        default="PREVIEW",
                        max_length=10,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=200)),
                ("rows", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("new_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("matched_count", models.PositiveIntegerField(default=0)),
                ("unmatched_count", models.PositiveIntegerField(default=0)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statement_imports",
                        to="payments.paymentaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("posted_on", models.DateField(verbose_name="date")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="description"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="reference"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MATCHED", "Matched"),
                            ("UNMATCHED", "Waiting to be matched"),
                            ("IGNORED", "Ignored"),
                        ],
                        default="UNMATCHED",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "matched_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REFERENCE", "Unit reference"),
                            ("MANUAL", "By hand"),
                        ],
                        max_length=10,
                    ),
                ),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "matched_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_transaction",
                        to="payments.payment",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_transactions",
                        to="payments.paymentaccount",
                    ),
                ),
                (
                    "suggested_lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leases.lease",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_lines",
                        to="banking.statementimport",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_on", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="statementimport",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="banking_sta_organiz_06255c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["organization", "status"], name="banking_ban_organiz_716147_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["payment_account", "posted_on"],
                name="banking_ban_payment_e011ae_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.UniqueConstraint(
                models.F("payment_account"),
                models.F("fingerprint"),
                name="banking_transaction_fingerprint_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="banking_transaction_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "MATCHED"), _negated=True),
                    ("payment__isnull", False),
                    _connector="OR",
                ),
                name="banking_transaction_matched_has_payment",
            ),
        ),
    ]
