# Generated by Django 6.1.1 on 2026-09-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statementimport",
            name="period_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statementimport",
            name="period_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
