# Generated by Django 6.1.1 on 2026-09-29 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0012_grant_owner_capabilities"),
        (
            "notifications",
            "0006_owner_statement_type",
        ),
        ("properties", "0005_property_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerRemittance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("month", models.DateField(verbose_name="statement month")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                ("paid_on", models.DateField(verbose_name="date paid")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("MPESA", "M-Pesa"),
                            ("BANK", "Bank transfer"),
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("OTHER", "Other"),
                        ],
                        default="MPESA",
                        max_length=10,
                        verbose_name="method",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="reference"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="note"),
                ),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, max_length=300, verbose_name="reason"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remittances",
                        to="properties.propertyowner",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_on", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="reports_remittance_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("month__day", 1)),
                        name="reports_remittance_month_first_day",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OwnerStatementSend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("month", models.DateField()),
                ("number", models.CharField(max_length=30)),
                (
                    "pdf",
                    models.FileField(editable=False, upload_to="owner-statements/%Y/"),
                ),
                ("collected", models.DecimalField(decimal_places=2, max_digits=14)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=14)),
                ("due", models.DecimalField(decimal_places=2, max_digits=14)),
                ("remitted", models.DecimalField(decimal_places=2, max_digits=14)),
                ("email_to", models.EmailField(blank=True, max_length=254)),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("NONE", "Not emailed"),
                            ("SENT", "Emailed"),
                            ("FAILED", "Email failed"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("email_error", models.CharField(blank=True, max_length=300)),
                ("sent_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statement_sends",
                        to="properties.propertyowner",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sms",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="notifications.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("organization"),
                        models.F("number"),
                        name="reports_statementsend_number_unique",
                    )
                ],
            },
        ),
    ]
