# Generated by Django 6.1.1 on 2026-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerstatementsend",
            name="expenses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
