# Generated by Django 6.1.1 on 2026-09-29 20:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_mfa"),
        ("expenses", "0001_initial"),
        ("leases", "0003_billing_frequency"),
        ("properties", "0005_property_owner"),
        ("tenants", "0003_tenant_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("number", models.CharField(editable=False, max_length=30)),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="what is wrong"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="details"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PLUMBING", "Plumbing"),
                            ("ELECTRICAL", "Electrical"),
                            ("WATER", "Water supply"),
                            ("DOORS", "Doors and locks"),
                            ("STRUCTURE", "Roof and walls"),
                            ("PAINTING", "Painting"),
                            ("APPLIANCES", "Appliances"),
                            ("PESTS", "Pests"),
                            ("SECURITY", "Security"),
                            ("CLEANING", "Cleaning and garbage"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=12,
                        verbose_name="kind",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency"),
                            ("HIGH", "High"),
                            ("NORMAL", "Normal"),
                            ("LOW", "Low"),
                        ],
                        default="NORMAL",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In progress"),
                            ("ON_HOLD", "On hold"),
                            ("DONE", "Done"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="NEW",
                        editable=False,
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("STAFF", "Staff"), ("PORTAL", "Tenant portal")],
                        default="STAFF",
                        editable=False,
                        max_length=6,
                    ),
                ),
                ("due_at", models.DateTimeField(verbose_name="due by")),
                (
                    "assigned_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "done_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cancel_reason",
                    models.CharField(blank=True, editable=False, max_length=300),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_requests",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_requests",
                        to="properties.property",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_requests",
                        to="expenses.supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_requests",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_requests",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="MaintenancePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "image",
                    models.ImageField(editable=False, upload_to="maintenance/%Y/"),
                ),
                ("width", models.PositiveIntegerField(editable=False)),
                ("height", models.PositiveIntegerField(editable=False)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("shared_with_tenant", models.BooleanField(default=False)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photos",
                        to="maintenance.maintenancerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("REPORTED", "Reported"),
                            ("STATUS", "Status"),
                            ("ASSIGNED", "Assigned"),
                            ("PRIORITY", "Priority"),
                            ("NOTE", "Note"),
                            ("COMMENT", "Tenant comment"),
                            ("PHOTO", "Photo"),
                            ("COST", "Cost"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In progress"),
                            ("ON_HOLD", "On hold"),
                            ("DONE", "Done"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In progress"),
                            ("ON_HOLD", "On hold"),
                            ("DONE", "Done"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=12,
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=1000)),
                ("shared_with_tenant", models.BooleanField(default=False)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updates",
                        to="maintenance.maintenancerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["at", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["organization", "status", "due_at"],
                name="maintenance_organiz_2fe6d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["property", "status"], name="maintenance_propert_ef7a40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["assigned_to", "status"], name="maintenance_assigne_70195a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancerequest",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                models.F("number"),
                name="maintenance_request_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancephoto",
            constraint=models.CheckConstraint(
                condition=models.Q(("width__gt", 0)), name="maintenance_photo_width"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceupdate",
            index=models.Index(
                fields=["request", "at"], name="maintenance_request_582a9b_idx"
            ),
        ),
    ]
