# Generated by Django 6.1.1 on 2026-09-29 12:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0011_grant_meter_capabilities"),
        ("leases", "0003_billing_frequency"),
        ("properties", "0005_property_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. A1 water, or the serial number",
                        max_length=60,
                        verbose_name="label",
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="serial number"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("POSTPAID", "Postpaid (billed from readings)"),
                            ("PREPAID", "Prepaid (not billed)"),
                        ],
                        default="POSTPAID",
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "split",
                    models.CharField(
                        choices=[("EQUAL", "Equally"), ("WEIGHTED", "By weight")],
                        default="EQUAL",
                        max_length=10,
                        verbose_name="shared meter split",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="rate per m³",
                    ),
                ),
                (
                    "minimum_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="minimum charge",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meters",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["property__name", "label"],
            },
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("read_on", models.DateField(verbose_name="reading date")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="reading (m³)"
                    ),
                ),
                (
                    "is_baseline",
                    models.BooleanField(
                        default=False, verbose_name="meter replaced / first reading"
                    ),
                ),
                ("flags", models.JSONField(blank=True, default=list, editable=False)),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="note"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, editable=False, upload_to="meter-readings/%Y/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Waiting for approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SUBMITTED",
                        editable=False,
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "minimum_charge",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "approval_note",
                    models.CharField(blank=True, editable=False, max_length=300),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "reject_reason",
                    models.CharField(blank=True, editable=False, max_length=300),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="meters.meter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="meters.meterreading",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-read_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="MeterCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_start", models.DateField()),
                ("service_end", models.DateField()),
                ("billing_month", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("description", models.CharField(max_length=200)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meter_charges",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="properties.unit",
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="meters.meterreading",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="MeterUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=6,
                        verbose_name="weight",
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="served",
                        to="meters.meter",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["unit__code"],
            },
        ),
        migrations.AddField(
            model_name="meter",
            name="units",
            field=models.ManyToManyField(
                related_name="meters", through="meters.MeterUnit", to="properties.unit"
            ),
        ),
        migrations.AddIndex(
            model_name="meterreading",
            index=models.Index(
                fields=["organization", "status"], name="meters_mete_organiz_c8d297_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meterreading",
            index=models.Index(
                fields=["meter", "read_on"], name="meters_mete_meter_i_5132b2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="meterreading",
            constraint=models.UniqueConstraint(
                models.F("meter"),
                models.F("read_on"),
                condition=models.Q(("status__in", ["SUBMITTED", "APPROVED"])),
                name="meters_reading_one_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="meterreading",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0)),
                name="meters_reading_value_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="meterreading",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_baseline", True), ("previous__isnull", False), _connector="OR"
                ),
                name="meters_reading_measured_from_previous",
            ),
        ),
        migrations.AddIndex(
            model_name="metercharge",
            index=models.Index(
                fields=["lease", "billing_month"], name="meters_mete_lease_i_794d36_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="metercharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="meters_charge_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="metercharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("service_end__gte", models.F("service_start"))),
                name="meters_charge_days_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="meterunit",
            constraint=models.UniqueConstraint(
                models.F("meter"), models.F("unit"), name="meters_meterunit_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="meterunit",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gt", 0)),
                name="meters_meterunit_weight_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="meter",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_charge__gte", 0), ("rate__gte", 0)),
                name="meters_meter_rates_not_negative",
            ),
        ),
    ]
