# Generated by Django 6.1.1 on 2026-09-29 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0007_grant_inspection_capabilities"),
        ("leases", "0002_lease_overlap_uses_actual_end"),
        ("properties", "0004_branding_and_branches"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("MOVE_IN", "Move-in"), ("MOVE_OUT", "Move-out")],
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        editable=False,
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("inspected_on", models.DateField(verbose_name="inspection date")),
                (
                    "tenant_present",
                    models.BooleanField(
                        default=False, verbose_name="tenant was present"
                    ),
                ),
                (
                    "tenant_comments",
                    models.TextField(blank=True, verbose_name="tenant's comments"),
                ),
                (
                    "keys_handed",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="keys handed over"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="general notes")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cancel_reason",
                    models.CharField(blank=True, editable=False, max_length=300),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="condition_reports",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="condition_reports",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-inspected_on", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ConditionReportLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(blank=True, max_length=60)),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                            ("DAMAGED", "Damaged"),
                            ("MISSING", "Missing"),
                            ("NOT_CHECKED", "Not checked"),
                        ],
                        max_length=12,
                        verbose_name="condition",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=300, verbose_name="note"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="inspections.conditionreport",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ConditionPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "image",
                    models.ImageField(
                        editable=False, upload_to="condition-reports/%Y/"
                    ),
                ),
                ("width", models.PositiveIntegerField(editable=False)),
                ("height", models.PositiveIntegerField(editable=False)),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="caption"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photos",
                        to="inspections.conditionreport",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photos",
                        to="inspections.conditionreportline",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="UnitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Kitchen, Bedroom 1",
                        max_length=60,
                        verbose_name="area",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="item")),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="quantity"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="note"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.AddField(
            model_name="conditionreportline",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report_lines",
                to="inspections.unititem",
            ),
        ),
        migrations.AddIndex(
            model_name="conditionreport",
            index=models.Index(
                fields=["unit", "kind", "status"], name="inspections_unit_id_553ecb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conditionreport",
            constraint=models.UniqueConstraint(
                models.F("lease"),
                models.F("kind"),
                condition=models.Q(("status", "CANCELLED"), _negated=True),
                name="inspections_report_one_per_lease_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="conditionreportline",
            constraint=models.UniqueConstraint(
                models.F("report"),
                models.F("item"),
                name="inspections_line_one_per_item",
            ),
        ),
    ]
