# Generated by Django 6.1.1 on 2026-09-26 13:47

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
import django.core.validators
import django.db.models.deletion
import leases.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("billing", "0001_initial"),
        ("properties", "0002_buildings_units_address"),
        ("tenants", "0001_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The overlap constraint compares unit ids (btree) and date ranges (gist) in one index.
        BtreeGistExtension(),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        verbose_name="lease number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ENDED", "Ended"),
                            ("TERMINATED", "Terminated"),
                            ("RENEWED", "Renewed"),
                        ],
                        default="DRAFT",
                        editable=False,
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "billing_frequency",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly")],
                        default="MONTHLY",
                        max_length=10,
                        verbose_name="billing",
                    ),
                ),
                (
                    "due_day",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Day of the month rent is due (1–28).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                        verbose_name="rent due day",
                    ),
                ),
                (
                    "grace_days",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Days after the due date before rent counts as late.",
                        validators=[django.core.validators.MaxValueValidator(31)],
                        verbose_name="grace days",
                    ),
                ),
                (
                    "notice_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[django.core.validators.MaxValueValidator(365)],
                        verbose_name="notice period (days)",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="deposit",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="KES", editable=False, max_length=3),
                ),
                ("terms", models.TextField(blank=True, verbose_name="terms and notes")),
                (
                    "activated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "notice_given_on",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                ("ended_on", models.DateField(blank=True, editable=False, null=True)),
                ("end_reason", models.TextField(blank=True, editable=False)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "previous_lease",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_leases",
                        to="leases.lease",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leases",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="LeaseCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="amount"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly")],
                        default="MONTHLY",
                        max_length=10,
                        verbose_name="billing",
                    ),
                ),
                ("active_from", models.DateField(verbose_name="from")),
                (
                    "active_to",
                    models.DateField(blank=True, null=True, verbose_name="until"),
                ),
                (
                    "charge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lease_charges",
                        to="billing.chargetype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["active_from", "pk"],
            },
        ),
        migrations.CreateModel(
            name="LeasePayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=16, verbose_name="phone")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. employer, spouse",
                        max_length=150,
                        verbose_name="name",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payers",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="LeaseRentChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_from", models.DateField(verbose_name="effective from")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="monthly rent"
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="reason"),
                ),
                ("notice_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rent_changes",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["effective_from"],
            },
        ),
        migrations.CreateModel(
            name="LeaseTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lease_tenants",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lease_links",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "tenant__name"],
            },
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["organization", "status"], name="leases_leas_organiz_6ea869_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["unit", "status"], name="leases_leas_unit_id_d203d6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="leases_lease_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_day__gte", 1), ("due_day__lte", 28)),
                name="leases_lease_due_day_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(("deposit_amount__gte", 0)),
                name="leases_lease_deposit_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                models.F("number"),
                condition=models.Q(("number", ""), _negated=True),
                name="leases_lease_org_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status", "ACTIVE")),
                expressions=[
                    ("unit", "="),
                    (
                        leases.models.DateRange(
                            "start_date", "end_date", models.Value("[]")
                        ),
                        "&&",
                    ),
                ],
                name="leases_lease_no_active_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="leasecharge",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="leases_leasecharge_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="leasecharge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("active_to__isnull", True),
                    ("active_to__gte", models.F("active_from")),
                    _connector="OR",
                ),
                name="leases_leasecharge_to_after_from",
            ),
        ),
        migrations.AddIndex(
            model_name="leasepayer",
            index=models.Index(
                fields=["organization", "phone"], name="leases_leas_organiz_f2e408_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leasepayer",
            constraint=models.UniqueConstraint(
                models.F("lease"), models.F("phone"), name="leases_leasepayer_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaserentchange",
            constraint=models.UniqueConstraint(
                models.F("lease"),
                models.F("effective_from"),
                name="leases_rentchange_one_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaserentchange",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="leases_rentchange_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="leasetenant",
            constraint=models.UniqueConstraint(
                models.F("lease"), models.F("tenant"), name="leases_leasetenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="leasetenant",
            constraint=models.UniqueConstraint(
                models.F("lease"),
                condition=models.Q(("is_primary", True)),
                name="leases_leasetenant_one_primary",
            ),
        ),
    ]
