# Generated by Django 6.1.1 on 2026-09-26 19:10

import django.contrib.postgres.constraints
import django.db.models.functions.comparison
import leases.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("leases", "0001_initial"),
        ("properties", "0002_buildings_units_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lease",
            name="leases_lease_no_active_overlap",
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ended_on__isnull", True),
                    ("ended_on__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="leases_lease_ended_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status", "DRAFT"), _negated=True),
                expressions=[
                    ("unit", "="),
                    (
                        leases.models.DateRange(
                            "start_date",
                            django.db.models.functions.comparison.Coalesce(
                                "ended_on", "end_date"
                            ),
                            models.Value("[]"),
                        ),
                        "&&",
                    ),
                ],
                name="leases_lease_no_overlap",
            ),
        ),
    ]
