# Generated by Django 6.1.1 on 2026-09-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0002_lease_overlap_uses_actual_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="billing_frequency",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("YEARLY", "Yearly"),
                ],
                default="MONTHLY",
                max_length=10,
                verbose_name="billing",
            ),
        ),
        migrations.AlterField(
            model_name="leasecharge",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("YEARLY", "Yearly"),
                ],
                default="MONTHLY",
                max_length=10,
                verbose_name="billing",
            ),
        ),
    ]
