# Generated by Django 6.1.1 on 2026-09-27 21:29

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_organization_quiet_hours"),
        ("billing", "0003_ledgerentry_payment"),
        ("leases", "0002_lease_overlap_uses_actual_end"),
        ("payments", "0001_initial"),
        ("tenants", "0003_tenant_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "Email"),
                            ("IN_APP", "In-app"),
                        ],
                        max_length=10,
                    ),
                ),
                ("granted", models.BooleanField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("STAFF", "Recorded by staff"),
                            ("SMS_REPLY", "SMS reply"),
                            ("PORTAL", "Tenant portal"),
                            ("IMPORT", "Import"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["organization", "tenant", "channel"],
                        name="notificatio_organiz_6dad84_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("tenant__isnull", False), ("user__isnull", True)),
                            models.Q(("tenant__isnull", True), ("user__isnull", False)),
                            _connector="OR",
                        ),
                        name="notifications_consent_one_recipient",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("invoice_issued", "Invoice issued"),
                            ("rent_due_soon", "Rent due soon"),
                            ("rent_overdue", "Rent overdue"),
                            ("payment_received", "Payment received"),
                            ("announcement", "Announcement"),
                            ("payment_pending_review", "Payment waiting for review"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "Email"),
                            ("IN_APP", "In-app"),
                        ],
                        max_length=10,
                    ),
                ),
                ("to", models.CharField(blank=True, max_length=254)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("sw", "Swahili")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                (
                    "skip_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RULE_DISABLED", "Switched off for the organization"),
                            ("OPTED_OUT", "Recipient opted out"),
                            ("NO_CONSENT", "No consent for the channel"),
                            ("CHANNEL_UNAVAILABLE", "Channel not available"),
                            ("NO_ADDRESS", "No phone or address"),
                            ("NO_TEMPLATE", "No text for the channel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=300)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("send_after", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=30)),
                ("provider_id", models.CharField(blank=True, max_length=100)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("dedupe_key", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="billing.invoice",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leases.lease",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="payments.payment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["status", "send_after"],
                        name="notificatio_status_048ca2_idx",
                    ),
                    models.Index(
                        fields=["organization", "tenant"],
                        name="notificatio_organiz_958828_idx",
                    ),
                    models.Index(
                        fields=["user", "channel", "read_at"],
                        name="notificatio_user_id_1ebcc5_idx",
                    ),
                    models.Index(
                        fields=["provider", "provider_id"],
                        name="notificatio_provide_2da388_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("tenant__isnull", False), ("user__isnull", True)),
                            models.Q(("tenant__isnull", True), ("user__isnull", False)),
                            _connector="OR",
                        ),
                        name="notifications_message_one_recipient",
                    ),
                    models.UniqueConstraint(
                        models.F("organization"),
                        models.F("dedupe_key"),
                        condition=models.Q(("dedupe_key", ""), _negated=True),
                        name="notifications_message_dedupe_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("invoice_issued", "Invoice issued"),
                            ("rent_due_soon", "Rent due soon"),
                            ("rent_overdue", "Rent overdue"),
                            ("payment_received", "Payment received"),
                            ("announcement", "Announcement"),
                            ("payment_pending_review", "Payment waiting for review"),
                        ],
                        max_length=50,
                        verbose_name="notification",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "Email"),
                            ("IN_APP", "In-app"),
                        ],
                        max_length=10,
                        verbose_name="channel",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("sw", "Swahili")],
                        max_length=2,
                        verbose_name="language",
                    ),
                ),
                ("body", models.TextField(max_length=1000, verbose_name="text")),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        models.F("organization"),
                        models.F("type"),
                        models.F("channel"),
                        models.F("language"),
                        condition=models.Q(("archived_at__isnull", True)),
                        name="notifications_template_live_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invoice_issued", "Invoice issued"),
                            ("rent_due_soon", "Rent due soon"),
                            ("rent_overdue", "Rent overdue"),
                            ("payment_received", "Payment received"),
                            ("announcement", "Announcement"),
                            ("payment_pending_review", "Payment waiting for review"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "Email"),
                            ("IN_APP", "In-app"),
                        ],
                        max_length=10,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("tenant__isnull", False), ("user__isnull", True)),
                            models.Q(("tenant__isnull", True), ("user__isnull", False)),
                            _connector="OR",
                        ),
                        name="notifications_preference_one_recipient",
                    ),
                    models.UniqueConstraint(
                        models.F("organization"),
                        models.F("tenant"),
                        models.F("type"),
                        models.F("channel"),
                        condition=models.Q(("tenant__isnull", False)),
                        name="notifications_preference_tenant_unique",
                    ),
                    models.UniqueConstraint(
                        models.F("organization"),
                        models.F("user"),
                        models.F("type"),
                        models.F("channel"),
                        condition=models.Q(("user__isnull", False)),
                        name="notifications_preference_user_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationNotificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("invoice_issued", "Invoice issued"),
                            ("rent_due_soon", "Rent due soon"),
                            ("rent_overdue", "Rent overdue"),
                            ("payment_received", "Payment received"),
                            ("announcement", "Announcement"),
                            ("payment_pending_review", "Payment waiting for review"),
                        ],
                        max_length=50,
                        verbose_name="notification",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                (
                    "channels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("SMS", "SMS"),
                                ("WHATSAPP", "WhatsApp"),
                                ("EMAIL", "Email"),
                                ("IN_APP", "In-app"),
                            ],
                            max_length=10,
                        ),
                        default=list,
                        help_text="In order of preference.",
                    ),
                ),
                (
                    "offsets",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SmallIntegerField(),
                        blank=True,
                        default=list,
                        help_text="Reminder days relative to the date the type is about.",
                    ),
                ),
                (
                    "include_co_tenants",
                    models.BooleanField(
                        default=False, verbose_name="also send to co-tenants"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        models.F("organization"),
                        models.F("type"),
                        name="notifications_rule_org_type_unique",
                    )
                ],
            },
        ),
    ]
