# Generated by Django 6.1.1 on 2026-09-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="provider_template",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="source",
            field=models.CharField(
                choices=[
                    ("STAFF", "Recorded by staff"),
                    ("SMS_REPLY", "SMS reply"),
                    ("WA_REPLY", "WhatsApp reply"),
                    ("PORTAL", "Tenant portal"),
                    ("IMPORT", "Import"),
                ],
                max_length=10,
            ),
        ),
    ]
