# Generated by Django 6.1.1 on 2026-09-28 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_organization_quiet_hours"),
        ("billing", "0003_ledgerentry_payment"),
        ("leases", "0002_lease_overlap_uses_actual_end"),
        ("notifications", "0003_whatsapp"),
        ("payments", "0002_receipt_share_token"),
        ("tenants", "0003_tenant_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="message",
            name="notifications_message_one_recipient",
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("invoice_issued", "Invoice issued"),
                    ("rent_due_soon", "Rent due soon"),
                    ("rent_overdue", "Rent overdue"),
                    ("payment_received", "Payment received"),
                    ("announcement", "Announcement"),
                    ("payment_pending_review", "Payment waiting for review"),
                    ("payment_unmatched", "Payment not matched (to the payer)"),
                    ("mpesa_unmatched", "M-Pesa payment not matched"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("invoice_issued", "Invoice issued"),
                    ("rent_due_soon", "Rent due soon"),
                    ("rent_overdue", "Rent overdue"),
                    ("payment_received", "Payment received"),
                    ("announcement", "Announcement"),
                    ("payment_pending_review", "Payment waiting for review"),
                    ("payment_unmatched", "Payment not matched (to the payer)"),
                    ("mpesa_unmatched", "M-Pesa payment not matched"),
                ],
                max_length=50,
                verbose_name="notification",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("invoice_issued", "Invoice issued"),
                    ("rent_due_soon", "Rent due soon"),
                    ("rent_overdue", "Rent overdue"),
                    ("payment_received", "Payment received"),
                    ("announcement", "Announcement"),
                    ("payment_pending_review", "Payment waiting for review"),
                    ("payment_unmatched", "Payment not matched (to the payer)"),
                    ("mpesa_unmatched", "M-Pesa payment not matched"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="organizationnotificationrule",
            name="type",
            field=models.CharField(
                choices=[
                    ("invoice_issued", "Invoice issued"),
                    ("rent_due_soon", "Rent due soon"),
                    ("rent_overdue", "Rent overdue"),
                    ("payment_received", "Payment received"),
                    ("announcement", "Announcement"),
                    ("payment_pending_review", "Payment waiting for review"),
                    ("payment_unmatched", "Payment not matched (to the payer)"),
                    ("mpesa_unmatched", "M-Pesa payment not matched"),
                ],
                max_length=50,
                verbose_name="notification",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tenant__isnull", False), ("user__isnull", True)),
                    models.Q(("tenant__isnull", True), ("user__isnull", False)),
                    models.Q(
                        ("tenant__isnull", True),
                        ("user__isnull", True),
                        models.Q(("to", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="notifications_message_one_recipient",
            ),
        ),
    ]
