# Generated by Django 6.1.1 on 2026-09-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_payer_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("invoice_issued", "Invoice issued"),
                    ("rent_due_soon", "Rent due soon"),
                    ("rent_overdue", "Rent overdue"),
                    ("payment_received", "Payment received"),
                    ("announcement", "Announcement"),
                    ("payment_pending_review", "Payment waiting for review"),
                    ("payment_unmatched", "Payment not matched (to the payer)"),
                    ("mpesa_unmatched", "M-Pesa payment not matched"),
                    ("mpesa_daily_summary", "M-Pesa daily summary"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("invoice_issued", "Invoice issued"),
                    ("rent_due_soon", "Rent due soon"),
                    ("rent_overdue", "Rent overdue"),
                    ("payment_received", "Payment received"),
                    ("announcement", "Announcement"),
                    ("payment_pending_review", "Payment waiting for review"),
                    ("payment_unmatched", "Payment not matched (to the payer)"),
                    ("mpesa_unmatched", "M-Pesa payment not matched"),
                    ("mpesa_daily_summary", "M-Pesa daily summary"),
                ],
                max_length=50,
                verbose_name="notification",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("invoice_issued", "Invoice issued"),
                    ("rent_due_soon", "Rent due soon"),
                    ("rent_overdue", "Rent overdue"),
                    ("payment_received", "Payment received"),
                    ("announcement", "Announcement"),
                    ("payment_pending_review", "Payment waiting for review"),
                    ("payment_unmatched", "Payment not matched (to the payer)"),
                    ("mpesa_unmatched", "M-Pesa payment not matched"),
                    ("mpesa_daily_summary", "M-Pesa daily summary"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="organizationnotificationrule",
            name="type",
            field=models.CharField(
                choices=[
                    ("invoice_issued", "Invoice issued"),
                    ("rent_due_soon", "Rent due soon"),
                    ("rent_overdue", "Rent overdue"),
                    ("payment_received", "Payment received"),
                    ("announcement", "Announcement"),
                    ("payment_pending_review", "Payment waiting for review"),
                    ("payment_unmatched", "Payment not matched (to the payer)"),
                    ("mpesa_unmatched", "M-Pesa payment not matched"),
                    ("mpesa_daily_summary", "M-Pesa daily summary"),
                ],
                max_length=50,
                verbose_name="notification",
            ),
        ),
    ]
