# Generated by Django 6.1.1 on 2026-09-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_unverified_codes_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("invoice_issued", "Invoice issued"),
                    ("rent_due_soon", "Rent due soon"),
                    ("rent_overdue", "Rent overdue"),
                    ("payment_received", "Payment received"),
                    ("announcement", "Announcement"),
                    ("payment_pending_review", "Payment waiting for review"),
                    ("payment_unmatched", "Payment not matched (to the payer)"),
                    ("owner_statement", "Owner statement summary (to the owner)"),
                    ("mpesa_unmatched", "M-Pesa payment not matched"),
                    ("mpesa_daily_summary", "M-Pesa daily summary"),
                    ("maintenance_update", "Maintenance update (to the tenant)"),
                    ("maintenance_supplier_job", "Maintenance job (to the supplier)"),
                    ("maintenance_reported", "Maintenance request reported"),
                    ("maintenance_assigned", "Maintenance job assigned"),
                    ("mpesa_unverified_codes", "M-Pesa codes to check"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("invoice_issued", "Invoice issued"),
                    ("rent_due_soon", "Rent due soon"),
                    ("rent_overdue", "Rent overdue"),
                    ("payment_received", "Payment received"),
                    ("announcement", "Announcement"),
                    ("payment_pending_review", "Payment waiting for review"),
                    ("payment_unmatched", "Payment not matched (to the payer)"),
                    ("owner_statement", "Owner statement summary (to the owner)"),
                    ("mpesa_unmatched", "M-Pesa payment not matched"),
                    ("mpesa_daily_summary", "M-Pesa daily summary"),
                    ("maintenance_update", "Maintenance update (to the tenant)"),
                    ("maintenance_supplier_job", "Maintenance job (to the supplier)"),
                    ("maintenance_reported", "Maintenance request reported"),
                    ("maintenance_assigned", "Maintenance job assigned"),
                    ("mpesa_unverified_codes", "M-Pesa codes to check"),
                ],
                max_length=50,
                verbose_name="notification",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("invoice_issued", "Invoice issued"),
                    ("rent_due_soon", "Rent due soon"),
                    ("rent_overdue", "Rent overdue"),
                    ("payment_received", "Payment received"),
                    ("announcement", "Announcement"),
                    ("payment_pending_review", "Payment waiting for review"),
                    ("payment_unmatched", "Payment not matched (to the payer)"),
                    ("owner_statement", "Owner statement summary (to the owner)"),
                    ("mpesa_unmatched", "M-Pesa payment not matched"),
                    ("mpesa_daily_summary", "M-Pesa daily summary"),
                    ("maintenance_update", "Maintenance update (to the tenant)"),
                    ("maintenance_supplier_job", "Maintenance job (to the supplier)"),
                    ("maintenance_reported", "Maintenance request reported"),
                    ("maintenance_assigned", "Maintenance job assigned"),
                    ("mpesa_unverified_codes", "M-Pesa codes to check"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="organizationnotificationrule",
            name="type",
            field=models.CharField(
                choices=[
                    ("invoice_issued", "Invoice issued"),
                    ("rent_due_soon", "Rent due soon"),
                    ("rent_overdue", "Rent overdue"),
                    ("payment_received", "Payment received"),
                    ("announcement", "Announcement"),
                    ("payment_pending_review", "Payment waiting for review"),
                    ("payment_unmatched", "Payment not matched (to the payer)"),
                    ("owner_statement", "Owner statement summary (to the owner)"),
                    ("mpesa_unmatched", "M-Pesa payment not matched"),
                    ("mpesa_daily_summary", "M-Pesa daily summary"),
                    ("maintenance_update", "Maintenance update (to the tenant)"),
                    ("maintenance_supplier_job", "Maintenance job (to the supplier)"),
                    ("maintenance_reported", "Maintenance request reported"),
                    ("maintenance_assigned", "Maintenance job assigned"),
                    ("mpesa_unverified_codes", "M-Pesa codes to check"),
                ],
                max_length=50,
                verbose_name="notification",
            ),
        ),
    ]
